### DISCUSSION TITLE
Where is the discovery document located?

### DISCUSSION THREAD

**Discussion by MuhammadUsamaMX** [Parkour-Vienna/distrust#16] [Q&A] [answered]
Hi there I'm trying to setup distrust as openid provider I setup app config but issue arises when I try to add sso info in workadventure settings. The error I got is 

> Well-known URI Discovery Mechanism resources not found for your domain: site/.well-known/openid-configuration

Here are the logs 
"1:08PM INF clients loaded numClients=1
1:08PM INF Starting server url=http://0.0.0.0:3000
1:09PM TRC request finished duration=0.026969 from=10.88.0.1:53030 method=GET path=/ status=307
1:11PM TRC request finished duration=0.023214 from=10.88.0.1:34124 method=GET path=/ status=307
1:12PM TRC request finished duration=0.071048 from=10.88.0.1:48716 method=GET path=/ status=307
1:12PM TRC request finished duration=0.032874 from=10.88.0.1:48716 method=GET path=/site status=404
1:12PM TRC request finished duration=0.016694 from=10.88.0.1:48716 method=GET path=/favicon.ico status=404
1:15PM INF clients loaded numClients=1
1:15PM INF Starting server url=http://0.0.0.0:3000"
Can you please share detail configuration steps because it is not working out for me morever there is not enough info.

**Comment by Aesgarth** [comment, marked as answer]
for me the discovery document is located at
site/oauth2/.well-known/openid-configuration

**Reply by theSuess** [reply]
This is the right answer. For example: if you host distrust at `https://auth.your-forum.com`, then the discovery endpoint will be: `https://auth.your-forum.com/oauth2/.well-known/openid-configuration`

**Reply by wahaj4311** [reply]
Suppose my site is x.com and I ran discourse using podman running at 0.0.0.0:3000. The oauth2 should be at x.com/oauth2/.well-known/openid-configuration But unfortunately it is not there. Any way to debug it.

**Reply by wahaj4311** [reply]
On distrust.yml 
I got a few confusion please correct me
the app id is right below the client ?
For secret also we will use the client secret on sso ??
Thank you.

**Reply by theSuess** [reply]
Distrust is intended to be run as a separate service. For example:

```
talk.example.com <-- your forum
auth.example.com <-- distrust
```

When configuring third party applications to use oauth, you can then exclusively use `auth.example.com` (with the discovery document `https://auth.your-forum.com/oauth2/.well-known/openid-configuration`)

**Reply by wahaj4311** [reply]
I really appreciate your replay. Thank you.
Maybe sometimes I'm too dumb to understand can you please have a look at my configuration?
```
server: https://forum.x(discourse).com/
  secret: somesecret (discourse)
oidc:
  secret: 'some-secret'
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
rsa key
    -----END RSA PRIVATE KEY-----

clients:
  demoid: -> application id ? (add in sso openid setting?)
    secret: 'secret' -> application secret?
    allowGroups: ['admin']
    redirectURIs:
      - 'https://x.com/oauth/demo/callback'

```

> the first section is of discourse the conf I use in discourse provider secret

> Second just added a secret 

> the third client section

- demoid (Is it the application id to add in sso openid settings?)
- secret (App secret)?
- redirect url I got from sso 

**What am i doing wrong?**

Sorry for any formatting issue I'm relatively new to posting on git.

Once again I really appreciate your help.
thanks you
